### ISSUE TITLE
HaruViewController 這個效果沒出來

### ISSUE THREAD

**Issue by studyBully** [DaidoujiChen/DaiLive2DPlayground#2]
- (void)setupLive2DModel {
  // 建置 live2d model 畫面
  self.live2DViewController = [HaruViewController new];
  self.live2DViewController.view.frame = self.view.bounds;
  [self.view addSubview:self.live2DViewController.view];
  [self.view bringSubviewToFront:self.floatingView];
  }

**Comment by DaidoujiChen** [comment]
Hello @studyBully,

我直接抓下來試試, 這幾天 `code4app` 那邊也有人說不行.

**Comment by DaidoujiChen** [comment]
好了!

**Comment by studyBully** [comment]
不对啊。我是刚刚从github上抓下来 进行run的。  iPhone 5S Xcode7.2  9.1的  但是还是不行啊。

**Comment by DaidoujiChen** [comment]
Hello @studyBully,

你先砍掉你硬盤裡的那份, 然後重新抓下一次,
我是在你回報之後才改好的.
